using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>
using System;

namespace SM.Lib.Helpers.Tests
{
    public partial class PriceCalculatorTest
    {

        [TestMethod]
        [PexGeneratedBy(typeof(PriceCalculatorTest))]
        public void CalculateVatPriceVoid494()
        {
            this.CalculateVatPriceVoid(0, 0);
        }
    }
}
