using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework;
// <auto-generated>
// This file contains automatically generated tests.
// Do not modify this file manually.
// 
// If the contents of this file becomes outdated, you can delete it.
// For example, if it no longer compiles.
// </auto-generated>
using System;

namespace SM.Lib.Helpers.Tests
{
    public partial class PriceCalculatorTest
    {

        [TestMethod]
        [PexGeneratedBy(typeof(PriceCalculatorTest))]
        public void MarginPrice719()
        {
            double d;
            d = this.MarginPrice(0, 0);
            PexAssert.AreEqual<double>(0, d);
        }
    }
}
